from dataclasses import dataclass


class DataIngetionArtifact:
    feature_store_file_path:str
    train_file_path:str
    test_file_path:str 


class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...